### ISSUE TITLE
Understanding of some functions？

### ISSUE THREAD

**Issue by QUIlToT** [FedUni/caliko#24]
Hello

Thank you for your generous sharing!

When I was learning your code, I didn’t quite understand the meaning of these functions, such as createRotationMatix, projectOntoPlane.

Especially this process : 

Mat3f m = Mat3f.createRotationMatrix( mChain.get(loop-1).getDirectionUV() )

Vec3f relativeHingeRotationAxis = m.times( thisBoneJoint.getHingeRotationAxis() ).normalise()

thisBoneOuterToInnerUV = thisBoneOuterToInnerUV.projectOntoPlane(relativeHingeRotationAxis);

Looking forward to your reply! 

If you're busy, could you recommend me some papers to understand this process?

Thanks!

**Comment by alansley** [comment]
Hi! All the methods are documented, so you can either have a look at the javadoc documentation, or at the source code for any given method (also the lines of code you mention should be commented with regard to what they're doing, but perhaps you're kinda confused as to _why_ they're doing it?). Anyways, I'll have a go at explaining...

If you point the first finger of your left hand at the screen (forward/Z-axis) with your thumb pointing upwards (up/Y-axis) (i.e. finger-gun!) then if you put your middle finger pointing to the right (right/X-axis) then that's basically a 3x3 'rotation matrix' - it contains the directions of the X/Y/Z axes. Each axis (i.e. finger) has a direction, and we can describe this direction as a set of three values which are just how much the finger/axis is pointing to the right, how much it's pointing up, and how much it's pointing forward.

For example the direction (1, 0, 0) would be "right" / positive-X-axis because it's fully to the right (X), nothing on Y, and nothing on Z.

However, this is just in the "global" / world coordinate system. If I'm doing my left-hand fingers-as-axes thing and I turn my body 90 degrees to the right then my fingers are still making the X/Y/Z axes... but these are now *local* / relative to **me**, rather than being the global / world directions. So this is kinda what's going on here:

1 - Generate a rotation matrix based on the direction of the "previous" (loop-1) bone in the IK chain
`Mat3f m = Mat3f.createRotationMatrix( mChain.get(loop-1).getDirectionUV() )`
The createRotationMatrix method creates a 3x3 matrix containing a set of orthogonal X/Y/Z axes (i.e. which way is right? (X), which way is up? (Y), and which way is forward? (Z)). Orthogonal just means that each axis is 90 degrees away from the other two axes [so "right" is 'up' rotated 90 degrees clockwise, and it's also 'forward' rotated 90 degrees clockwise]. So basically we're getting the coordinate system of that bone, i.e. which way us right/up/forward (X/Y/Z) for that bone. BTW, getDirectionUV gets the direction of the bone (i.e. the direction from the base of the bone to the tip of the bone as a _unit-vector_, that is, each value in the X/Y/Z triplet is in the range -1 to +1).

2 - Convert the hinge rotation axis into the coordinate system of the bone in the IK chain
`Vec3f relativeHingeRotationAxis = m.times( thisBoneJoint.getHingeRotationAxis() ).normalise()`
The hinge rotation axis is the direction about which the hinge rotates. For example, if you think of the door to your house - the hinge rotation axis would be the Y-axis so that the door can open and close about that axis. However, if you think of a "doggy-door" or cat-flap, then the hinge rotation axis would be the X-axis because they open by rotating from the bottom upwards.  

When we specify a hinge rotation axis for a joint (which is at the start of the IK bone), we specify it in **world-space** because that's the only sensible option - but when we come to actually _use_ the hinge rotation axis the bone has probably moved so we need to transform its hinge rotation axis from world-space into local-space (i.e. the coordinate system of the bone itself) - the way that we can do this is to multiply the hinge rotation axis by the rotation matrix of the bone, which we just calculated in step 1.

So what we're really doing is placing the hinge rotation axis of THIS bone into the coordinate system of the PREVIOUS bone in the chain (because in this part of the code we're working from the tip of the IK chain to the base of the chain during the "forward" pass).

The final `.normalise()` part just keeps all the values as unit-vectors (i.e. the value of each component (X/Y/Z) is confined to the range -1 to +1. This helps us to prevent weird math issues occuring when we actually go to do things with the direction later on!)

3 - Project this (outer) bone's direction onto the plane described by the hinge rotation axis we just calculated
`thisBoneOuterToInnerUV = thisBoneOuterToInnerUV.projectOntoPlane(relativeHingeRotationAxis);`
What we're doing in this part is getting the bone direction (well, technically the opposite direction to the bone because we're working from the outer joint to the inner joint, i.e. finger-tip to base-of-finger, but that doesn't matter right now) into the plane of the hinge rotation axis so we can restrict it to any clockwise/anti-clockwise limits (as specified by the bone's joint).

As we discussed above, hinges (i.e. doors, cat-flaps etc) have a hinge-rotation axis - this direction / axis is enough information for us to describe the plane (i.e. a flat surface) about which the rotation occurs. For example, the floor (or the ceiling, I guess - but then clockwise & anti-clockwise would go in the opposite directions!) is the plane of rotation for a standard door. Another way to think of it might be like putting a pencil pointing directly upwards on your desk - the plane about which you can rotate about the pencil describes the plane of your desk. If you put the pencil with its base against a wall pointing directly outwards, then the plane about the pencil's direction is the plane of the wall. So what we're doing here is projecting (i.e. converting) the direction of this bone so that it lies in the plane described by the hinge rotation axis.

Not sure if this is making sense - maybe think of it this way: If you have a pencil on your desk pointing up-right at 45 degrees, and you have a lamp directly to the left and above the pencil, then the **shadow** of the pencil on the desk is the direction of the pencil projected onto the plane of the desk. Now that the hinge rotation axis and the projected direction of the bone are both in the same plane, we can compare the bone's direction to any clockwise and anti-clockwise hinge rotation limits and move the bone direction back if it exceeds those limits, thus limiting how far any bone can rotate about its hinge rotation axis.

Hope this helps!

**Comment by QUIlToT** [comment]
Thanks, I learned a lot from your reply! 

But I have one last question, what's the meaning of BaseboneConstraintType(i.e. rotor)?

I know the Hinge joint, just like the normal manipulator joint, but what about the Rotor?  Does the Rotor equal to the twist joint? 

Thanks!

**Comment by alansley** [comment]
No worries!

From: https://github.com/FedUni/caliko/blob/master/caliko/src/main/java/au/edu/federation/caliko/FabrikChain3D.java

```
public enum BaseboneConstraintType3D implements BaseboneConstraintType
{
	NONE,         // No constraint - basebone may rotate freely
	GLOBAL_ROTOR, // World-space rotor constraint
	LOCAL_ROTOR,  // Rotor constraint in the coordinate space of (i.e. relative to) the direction of the connected bone
	GLOBAL_HINGE, // World-space hinge constraint
	LOCAL_HINGE   // Hinge constraint in the coordinate space of (i.e. relative to) the direction of the connected bone
}
```

So, hinges are hinges like on a door etc. as we've discussed, and the hinge rotation axis can be specified in either local or global (i.e. "world-space") coordinates. Rotors aren't quite the twist, they're the angle relative to a given world-space direction (GLOBAL_ROTOR), or the angle relative to the direction of the connected bone (LOCAL_ROTOR).

If you take a look at the documentation at:
https://github.com/FedUni/caliko/blob/master/caliko-distribution/src/site/docs/caliko-user-guide.pdf

Then page 11 has details of joint types. If you then take a look at page 12 there's a GLOBAL_ROTOR constraint displayed as a red cone (top-left image, "Demo 3") - the bone cannot move outside of the angle described by the cone. 

You can see the different joint types in action in the library demonstration video on youtube:
https://youtu.be/wEtp4P2ucYk?t=212

Hope this helps!

**Comment by QUIlToT** [comment]
Thank u! It truely helps a lot!
