### ISSUE TITLE
Is it possible to solve each chain with different target?

### ISSUE THREAD

**Issue by kolenda** [FedUni/caliko#3]
Hi Al,

First of all - Big thank you for this library and making it free to use and play with. For the last few days I've been rewriting it to C++ and learning how to use it but I've found this potential issue.

I'm trying to use it for character IK where I'll set the ends of all limbs and let the IK solve my skeleton, but while playing with the code I've found that you use only single target location for every chain.

It would be easy change to pass separate target to each chain, that's not a problem, but I'm not too familiar with the FABRIC itself yet so I'm not sure if I won't break anything else.
Do you think that just passing a different targets could work?

BTW I'm sorry I'm asking you by creating an Issue, but I couldn't find any other way to post a message :(. Feel free to delete this Issue to keep your repo clean.

Regards,
kolenda

**Comment by alansley** [comment]
Hi Kolenda,

You're very welcome - I'm glad you like the library and have found something cool to do with it!

As you say, the functionality currently exists for each chain to have its own target, however what I think you mean is that every **structure** (which may contain multiple chains - and where chains may or may not be connected to each other) uses the same target location, so a call to solveTarget on a structure solves every chain in the structure for that _same target location_ rather than having per-chain targets.

I've actually already flagged this functionality in the **TODO** section of the README.md (right at the bottom), where it says:

_Add mechanism for individual IK chains in a structure to be updated to individual target locations (i.e. each chain holds a reference to a Vec2f/Vec3f which can be updated) so that a single call to structure.updateEmbeddedTargets() can then update each chain in the structure for its own specific target locations._

Can the FABRIK algorithm handle this? Absolutely! You can see multiple effectors (i.e. targets) in a single "structure" (although I'm not sure if that's the term Andreas Aristidou uses) towards the end of his FABRIK video here: [https://www.youtube.com/watch?v=tN6RQ4yrNPU](https://www.youtube.com/watch?v=tN6RQ4yrNPU)

What we probably **don't** want to do is have each chain hold its own _copy_ of a target, because it may get out of sync with other chains copies of the "same target" - we want a reference / pointer to a target that exists independently of any given chain, but which may be assigned to any chain and then updated independently, so any chains using that target always have the most up-to-date version (because there's only one version!).

Then, you can write a simple "update" method for the structure without needing to pass a target location, and each chain gets solved for the target associated with it.

I may be able to find some time to implement this, but if you'd like to have a go at it then please do!

I think this is as good a place for any to raise an "issue" - I've just flagged it as an enhancement rather than a bug. Also, if/when you complete your C++ port, have you considered whether you'll make the source available? You aren't required to, because I released Caliko under the MIT license, but open is good and "a rising tide lifts all ships" etc.

Best wishes,
Al

P.S. For character IK you may have to be careful about the order in which chains are added to the structure because they get solved in a first-added-first-solved manner. I haven't experimented with whether this can impact the final IK solutions, although my suspicion would be that it does if there are joint restrictions. And then there's the whole topic of connecting _structures_ together!

**Comment by kolenda** [comment]
Hi Al,

Thank you for your response.
I didn't want to use more structures because as I understand it they are separate and can't be connected as chains, and for a character skeleton I need few connected chains, but each of them will have its own target location.
I'm going to test this approach but (un)fortunately I'm going to holiday for a week, but definitely will let you know how it ended.

And about releasing sources - I think about it and I'd really like to do so but I'm doing this as a part of my daily job so it's not my decision unfortunately. However I'll try to convince my boss it's worth it :).

Best,
kolenda

**Comment by alansley** [comment]
Ability to solve chains for embedded targets added in v1.2 release =D
